### ISSUE TITLE
Windos 10 - Start Menu 

### ISSUE THREAD

**Issue by eredeli** [cook-company/kiosk#286]
App does not starts from startup menu. It's opening from browser, not like in Windows 7 (separate opening). Application is not opening.

**Comment by matt-cook** [comment]
Closing since we now have a native Windows version: https://kiosk.cook.company/get-started please create a new ticket if you continue to see issues with version 9.0.4 or later.

**Comment by akeilox** [comment]
cant seem to open the website. Is there an alternate download link for the windows version?

been using the chrome extension for a while and would like to give the windows native a spin.

**Comment by matt-cook** [comment]
Bad timing, we had an issue with the site due to some unplanned SSL configuration changes. The direct link for the the current 64 bit windows version is: https://cdn.cook.company/kiosk/releases/9.0.4/kiosk-9.0.4-win-x64-setup.exe
32 bit: https://cdn.cook.company/kiosk/releases/9.0.4/kiosk-9.0.4-win-x86-setup.exe
