### ISSUE TITLE
Kiosk not auto-launching on ChromeOS version 70

### ISSUE THREAD

**Issue by TheWizz** [cook-company/kiosk#298]
This is likely a bug in ChromeOS, rather than in the Kiosk app, so this issue is more to see if others experience the same thing when attempting to install Kiosk. Everything installs OK, wih the reguar procedure (this is on an ASUS pre-2017 ChromeBox, so no need for the Google "management console" mess). I select the "auto-launch" feature of the Kiosk app, as usual. However, upon restart, Kiosk doesn't start. ChromeOS always arrives at the normal log-in screen. I can then start Kiosk manually from the "tray" without having to log in. It launches and runs in full screen mode, including all its settings and such. But it never auto-launches on start-up.

Any thoughts?

-JM

**Comment by j-applese3d** [comment]
I've run into the same issue. (I also have an older Asus Chromebox, so possibly it's hardware related? Though I doubt that.) I had to revert my Chromebox. You can do that by pressing Ctrl+Alt+Shift+R twice on the login page (when it boots up). (this reverted Chrome OS back to 69, which worked like a charm)

I appreciate you opening this issue, otherwise I'd have thought it was just myself having this problem.

**Comment by matt-cook** [comment]
Closing since this appears to be fixed in later versions of ChromeOS. Thanks for the bug report!
